//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVPClocker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVPClocker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жив.
        /// </summary>
        internal static string sAlive {
            get {
                return ResourceManager.GetString("sAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убит.
        /// </summary>
        internal static string sKilled {
            get {
                return ResourceManager.GetString("sKilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///появится через {1} мин..
        /// </summary>
        internal static string sKnownResp {
            get {
                return ResourceManager.GetString("sKnownResp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возрождается
        ///{0}!
        ///Пора убивать!.
        /// </summary>
        internal static string sMobResped {
            get {
                return ResourceManager.GetString("sMobResped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} минут.
        /// </summary>
        internal static string sTime {
            get {
                return ResourceManager.GetString("sTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Н/Д.
        /// </summary>
        internal static string sUnknown {
            get {
                return ResourceManager.GetString("sUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изветных респов нет.
        /// </summary>
        internal static string sUnknownResp {
            get {
                return ResourceManager.GetString("sUnknownResp", resourceCulture);
            }
        }
    }
}
